spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/reserve
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: h2

  jwt:
    secret: emVyb2Jhc2Utc3ByaW5nLWJvb3QtYXNzaWdubWVudC1kYXRhLXdpdGgtand0LXNlY3JldC1rZXk=

logging.level:
  org.hibernate.SQL: debug