spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mariadb://localhost:3306/reserve?characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: kk2924140

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect

  jwt:
    secret: emVyb2Jhc2Utc3ByaW5nLWJvb3QtYXNzaWdubWVudC1kYXRhLXdpdGgtand0LXNlY3JldC1rZXk=

logging.level:
  org.hibernate.SQL: debug